server:
  port: 8080

spring:
  application:
    name: cyxz-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yml
  config:
    import:
      - optional:nacos:
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400}
