server:
  port: 8080

spring:
  application:
    name: cyxz-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import:
      - optional:nacos:
