/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CircleCard: typeof import('./src/components/CircleCard.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    CreatorAgreement: typeof import('./src/components/creator/CreatorAgreement.vue')['default']
    CreatorContent: typeof import('./src/components/creator/CreatorContent.vue')['default']
    CreatorData: typeof import('./src/components/creator/CreatorData.vue')['default']
    CreatorFans: typeof import('./src/components/creator/CreatorFans.vue')['default']
    CreatorHome: typeof import('./src/components/creator/CreatorHome.vue')['default']
    CreatorInteraction: typeof import('./src/components/creator/CreatorInteraction.vue')['default']
    CreatorMagic: typeof import('./src/components/creator/CreatorMagic.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    ImageCarousel: typeof import('./src/components/ImageCarousel.vue')['default']
    ImageCropper: typeof import('./src/components/ImageCropper.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MasonryGrid: typeof import('./src/components/MasonryGrid.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PillTabs: typeof import('./src/components/PillTabs.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    UnderlineTabs: typeof import('./src/components/UnderlineTabs.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
