/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    ImageCropper: typeof import('./src/components/ImageCropper.vue')['default']
    IPhBell: typeof import('~icons/ph/bell')['default']
    IPhChatCircleText: typeof import('~icons/ph/chat-circle-text')['default']
    IPhMagnifyingGlass: typeof import('~icons/ph/magnifying-glass')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhPencilSimple: typeof import('~icons/ph/pencil-simple')['default']
    IPhPlus: typeof import('~icons/ph/plus')['default']
    IPhStar: typeof import('~icons/ph/star')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
  }
}
