server:
  port: 9008

spring:
  application:
    name: cyxz-search
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yml
  config:
    import:
      - "optional:nacos:${spring.application.name}.yml"
  elasticsearch:
    uris: http://${ES_HOST:127.0.0.1}:${ES_PORT:9200}
    connection-timeout: 30s
    socket-timeout: 60s
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
