server:
  port: 9005

spring:
  application:
    name: cyxz-search
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yml
  config:
    import:
      - optional:nacos:
  elasticsearch:
    uris: http://${ES_HOST:127.0.0.1}:${ES_PORT:9200}
    connection-timeout: 30s
    socket-timeout: 60s
