server:
  port: 9005

spring:
  application:
    name: cyxz-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import:
      - optional:nacos:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password:
